from pathlib import Path

path = Path('app/src/main/java/com/fantest/pokervision/VisionActivityV025.java')
text = path.read_text(encoding='utf-8')

old_manual = '''        CardFaceView preview = new CardFaceView(this);\n        preview.setCompact(false);\n\n        Runnable refreshSelection = () -> {\n            for (Button b : rankButtons) {\n                int rank = (Integer)b.getTag();\n                boolean on = rank == selectedRank[0];\n                b.setAlpha(on ? 1f : .52f);\n                b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(on ? PANEL2 : Color.rgb(222, 228, 225)));\n                b.setTextColor(on ? Color.WHITE : BG);\n            }\n            for (Button b : suitButtons) {\n                int suit = (Integer)b.getTag();\n                boolean on = suit == selectedSuit[0];\n                b.setAlpha(on ? 1f : .52f);\n                b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(on ? PANEL2 : Color.rgb(222, 228, 225)));\n                b.setTextColor((suit == 1 || suit == 2) ? RED : Color.BLACK);\n            }\n            preview.setCard(new PokerMath.Card(selectedRank[0], selectedSuit[0]));\n        };'''

new_manual = '''        CardFaceView preview = new CardFaceView(this);\n        preview.setCompact(false);\n        TextView availabilityStatus = text("", 11, RED, true);\n        availabilityStatus.setGravity(Gravity.CENTER);\n        final Button[] saveButton = {null};\n\n        Runnable refreshSelection = () -> {\n            PokerMath.Card currentSlotCard = table.selectedCard();\n            for (Button b : rankButtons) {\n                int rank = (Integer)b.getTag();\n                boolean anyAvailable = false;\n                for (int suit = 0; suit < 4; suit++) {\n                    PokerMath.Card option = new PokerMath.Card(rank, suit);\n                    if (!CardAvailability.isUsedElsewhere(option, currentSlotCard, table.holeCards(), table.boardCards())) {\n                        anyAvailable = true;\n                        break;\n                    }\n                }\n                boolean on = rank == selectedRank[0];\n                b.setEnabled(anyAvailable);\n                b.setAlpha(anyAvailable ? (on ? 1f : .52f) : .22f);\n                b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(on && anyAvailable ? PANEL2 : Color.rgb(222, 228, 225)));\n                b.setTextColor(anyAvailable ? (on ? Color.WHITE : BG) : Color.GRAY);\n            }\n            for (Button b : suitButtons) {\n                int suit = (Integer)b.getTag();\n                PokerMath.Card option = new PokerMath.Card(selectedRank[0], suit);\n                boolean used = CardAvailability.isUsedElsewhere(option, currentSlotCard, table.holeCards(), table.boardCards());\n                boolean on = suit == selectedSuit[0];\n                b.setEnabled(!used);\n                b.setAlpha(used ? .22f : (on ? 1f : .52f));\n                b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(on && !used ? PANEL2 : Color.rgb(222, 228, 225)));\n                b.setTextColor(used ? Color.GRAY : ((suit == 1 || suit == 2) ? RED : Color.BLACK));\n            }\n            PokerMath.Card candidate = new PokerMath.Card(selectedRank[0], selectedSuit[0]);\n            boolean used = CardAvailability.isUsedElsewhere(candidate, currentSlotCard, table.holeCards(), table.boardCards());\n            preview.setCard(candidate);\n            preview.setAlpha(used ? .25f : 1f);\n            availabilityStatus.setText(used ? (arabic ? "هذه البطاقة مستخدمة بالفعل" : "Already selected — choose another card") : "");\n            availabilityStatus.setVisibility(used ? View.VISIBLE : View.INVISIBLE);\n            if (saveButton[0] != null) {\n                saveButton[0].setEnabled(!used);\n                saveButton[0].setAlpha(used ? .42f : 1f);\n            }\n        };'''

old_preview_add = '''        previewHolder.addView(preview, previewLp);\n        box.addView(previewHolder, lp(-1, dp(120), 0, 0, 0, 10));\n\n        LinearLayout bottom = row();'''
new_preview_add = '''        previewHolder.addView(preview, previewLp);\n        box.addView(previewHolder, lp(-1, dp(120), 0, 0, 0, 4));\n        box.addView(availabilityStatus, lp(-1, dp(24), 0, 0, 0, 6));\n\n        LinearLayout bottom = row();'''

old_add = '''        Button add = dialogPrimaryButton(existing == null ? (arabic ? "إضافة" : "Add") : (arabic ? "استبدال" : "Replace"));\n        add.setOnClickListener(v -> {\n            PokerMath.Card c = new PokerMath.Card(selectedRank[0], selectedSuit[0]);\n            if (placeSelected(c, true)) {\n                toast(arabic ? "تم حفظ البطاقة" : c.pretty() + " saved");\n                dialog.dismiss();\n            }\n        });'''
new_add = '''        Button add = dialogPrimaryButton(existing == null ? (arabic ? "إضافة" : "Add") : (arabic ? "استبدال" : "Replace"));\n        saveButton[0] = add;\n        add.setOnClickListener(v -> {\n            PokerMath.Card c = new PokerMath.Card(selectedRank[0], selectedSuit[0]);\n            if (CardAvailability.isUsedElsewhere(c, table.selectedCard(), table.holeCards(), table.boardCards())) {\n                toast(arabic ? "هذه البطاقة مستخدمة بالفعل" : "That card is already selected");\n                refreshSelection.run();\n                return;\n            }\n            if (placeSelected(c, true)) {\n                toast(arabic ? "تم حفظ البطاقة" : c.pretty() + " saved");\n                dialog.dismiss();\n            }\n        });'''

old_guide = '''                    face.setCompact(true);\n                    face.setCard(c);\n                    face.setOnClickListener(v -> {\n                        if (placeSelected(c, true)) {\n                            toast((arabic ? "تمت إضافة " : "Added ") + c.pretty());\n                            dialog.dismiss();\n                        }\n                    });'''
new_guide = '''                    face.setCompact(true);\n                    face.setCard(c);\n                    boolean used = CardAvailability.isUsedElsewhere(c, table.selectedCard(), table.holeCards(), table.boardCards());\n                    face.setEnabled(!used);\n                    face.setAlpha(used ? .22f : 1f);\n                    face.setContentDescription(used ? (arabic ? "بطاقة مستخدمة" : "Card already selected") : c.pretty());\n                    if (!used) {\n                        face.setOnClickListener(v -> {\n                            if (placeSelected(c, true)) {\n                                toast((arabic ? "تمت إضافة " : "Added ") + c.pretty());\n                                dialog.dismiss();\n                            }\n                        });\n                    }'''

old_scanner = '''            Button b = cardCandidateButton(c);\n            b.setOnClickListener(v -> {\n                if (placeSelected(c, true)) {\n                    toast((arabic ? "تم حفظ " : "Saved ") + c.pretty());\n                    updateScannerTarget();\n                    if (table.holeComplete() && table.boardComplete()) closeScanner();\n                }\n            });'''
new_scanner = '''            Button b = cardCandidateButton(c);\n            boolean used = CardAvailability.isUsedElsewhere(c, table.selectedCard(), table.holeCards(), table.boardCards());\n            b.setEnabled(!used);\n            b.setAlpha(used ? .28f : 1f);\n            if (!used) {\n                b.setOnClickListener(v -> {\n                    if (placeSelected(c, true)) {\n                        toast((arabic ? "تم حفظ " : "Saved ") + c.pretty());\n                        updateScannerTarget();\n                        if (table.holeComplete() && table.boardComplete()) closeScanner();\n                    }\n                });\n            }'''

replacements = [
    (old_manual, new_manual),
    (old_preview_add, new_preview_add),
    (old_add, new_add),
    (old_guide, new_guide),
    (old_scanner, new_scanner),
]

for old, new in replacements:
    if old not in text:
        raise SystemExit('Expected v0.2.9 source fragment not found:\n' + old[:180])
    text = text.replace(old, new, 1)

path.write_text(text, encoding='utf-8')
patched = path.read_text(encoding='utf-8')
assert 'Already selected — choose another card' in patched
assert 'face.setAlpha(used ? .22f : 1f);' in patched
assert 'b.setAlpha(used ? .28f : 1f);' in patched
assert 'CardAvailability.isUsedElsewhere' in patched
print('v0.2.9 used-card availability patch applied successfully')
